# Generated by Django 2.1.2 on 2019-06-25 08:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='sample_1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_10',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_3',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_4',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_5',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_6',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_7',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_8',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_9',
        ),
        migrations.AddField(
            model_name='item',
            name='book_name',
            field=models.CharField(default='二ソリBook', max_length=100, verbose_name='書籍名'),
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='書籍説明'),
        ),
        migrations.AddField(
            model_name='item',
            name='provide_start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='提供開始日'),
        ),
        migrations.AddField(
            model_name='item',
            name='provider',
            field=models.CharField(default='二ソリ太郎', max_length=50, verbose_name='提供者'),
        ),
    ]
