# Generated by Django 2.1.2 on 2019-07-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rent_date',
            field=models.DateField(blank=True, null=True, verbose_name='貸出日'),
        ),
        migrations.AddField(
            model_name='item',
            name='renter',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='貸出者'),
        ),
    ]
