# Generated by Django 2.1.2 on 2019-06-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190625_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='provider',
            field=models.CharField(default='', max_length=50, verbose_name='提供者'),
        ),
    ]
