# Generated by Django 2.1.2 on 2019-07-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190717_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='provider',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='提供者'),
        ),
    ]
