# Generated by Django 2.1.2 on 2019-07-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190625_1756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'ブックスタンドマネージャー', 'verbose_name_plural': 'ブックスタンドマネージャー'},
        ),
        migrations.AddField(
            model_name='item',
            name='rent_status',
            field=models.CharField(choices=[(10, '貸出可能'), (20, '貸出中'), (30, '提供終了')], default='貸出可能', editable=False, max_length=10, verbose_name='貸出ステータス'),
        ),
        migrations.AlterField(
            model_name='item',
            name='book_name',
            field=models.CharField(default='', max_length=100, verbose_name='書籍名'),
        ),
    ]
