# Generated by Django 2.1.2 on 2019-07-17 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_item_provider_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='provider_id',
        ),
        migrations.AlterField(
            model_name='item',
            name='provider',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='提供者ID'),
        ),
    ]
