# Generated by Django 2.1.2 on 2019-07-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190717_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='provider_by',
        ),
        migrations.AddField(
            model_name='item',
            name='provide_by',
            field=models.IntegerField(default=1, editable=False, verbose_name='提供者ID'),
        ),
    ]
