# Generated by Django 2.1.2 on 2019-07-17 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190717_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='provide_by',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='提供者ID'),
        ),
    ]
