# Generated by Django 2.1.2 on 2019-07-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190717_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='provider',
            field=models.CharField(default='', editable=False, max_length=50, verbose_name='提供者'),
        ),
    ]
