# Generated by Django 2.1.2 on 2019-07-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190717_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='renter',
            field=models.CharField(blank=True, choices=[(1, ''), (2, '')], max_length=50, null=True, verbose_name='貸出者'),
        ),
    ]
