# Generated by Django 2.1.2 on 2019-07-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190723_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='renter',
            field=models.CharField(blank=True, choices=[(1, 'admin'), (2, '亀谷理恵')], max_length=50, null=True, verbose_name='貸出者'),
        ),
    ]
