# Generated by Django 2.1.2 on 2019-07-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190723_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='provide_by',
        ),
        migrations.AlterField(
            model_name='item',
            name='provider',
            field=models.IntegerField(choices=[(1, 'admin'), (2, '亀谷理恵')], default=1, verbose_name='提供者'),
        ),
    ]
