# Generated by Django 2.1.2 on 2019-07-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20190723_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='provider',
            field=models.IntegerField(choices=[(1, 'adminユーザー'), (2, '亀谷理恵'), (3, '桐原 智己')], default=1, editable=False, verbose_name='提供者'),
        ),
        migrations.AlterField(
            model_name='item',
            name='renter',
            field=models.IntegerField(blank=True, choices=[(1, 'adminユーザー'), (2, '亀谷理恵'), (3, '桐原 智己')], editable=False, null=True, verbose_name='貸出者'),
        ),
    ]
